CREATE TABLE `fieldinfo` (
	`idx` INT(11) NOT NULL AUTO_INCREMENT,
	`Source` VARCHAR(50) NULL DEFAULT NULL,
	`Field` VARCHAR(50) NULL DEFAULT NULL,
	`end` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`start` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	PRIMARY KEY (`idx`),
	UNIQUE INDEX `UNQ_SourceField` (`Field`, `Source`),
	INDEX `IDX_start` (`start`),
	INDEX `IDX_end` (`end`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `sourcedata` (
	`idx` INT(11) NOT NULL AUTO_INCREMENT,
	`Source` VARCHAR(50) NULL DEFAULT NULL,
	`SourceData` BLOB NULL,
	`UnixTimeStamp` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	PRIMARY KEY (`idx`),
	INDEX `IDX_Source` (`Source`),
	INDEX `IDX_UnixTimeStamp` (`UnixTimeStamp`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `metricinfo` (
	`idx` INT(11) NOT NULL AUTO_INCREMENT,
	`ObjectId` VARCHAR(50) NULL DEFAULT NULL,
	`Metric` VARCHAR(50) NULL DEFAULT NULL,
	`end` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`start` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	PRIMARY KEY (`idx`),
	UNIQUE INDEX `UNQ_Keys` (`ObjectId`, `Metric`),
	INDEX `IDX_start` (`start`),
	INDEX `IDX_end` (`end`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `objectdata` (
	`idx` INT(11) NOT NULL AUTO_INCREMENT,
	`ObjectId` VARCHAR(50) NULL DEFAULT NULL,
	`ObjectData` BLOB NULL,
	`UnixTimeStamp` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	PRIMARY KEY (`idx`),
	UNIQUE INDEX `UNQ_Keys` (`objectid`, `UnixTimeStamp`),
	INDEX `IDX_ObjectId` (`objectid`),
	INDEX `IDX_UnixTimeStamp` (`UnixTimeStamp`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE DEFINER=`root`@`localhost` FUNCTION `SPLIT_TEXT`(`x` LONGTEXT, `delim` VARCHAR(12), `pos` INT)
	RETURNS longtext CHARSET utf8
	LANGUAGE SQL
	DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
RETURN REPLACE(SUBSTRING(SUBSTRING_INDEX(x, delim, pos),
       CHAR_LENGTH(SUBSTRING_INDEX(x, delim, pos - 1)) + 1),
       delim, '');

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DynamicQueryExecuter`(IN `queryText` LONGTEXT)
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
	SET @count = 1;
	WHILE SPLIT_TEXT(queryText, ';', @count) != '' DO
		SET @SQLString = SPLIT_TEXT(queryText, ';', @count);
		PREPARE st FROM @SQLString;
		EXECUTE st;
		DEALLOCATE PREPARE st;
	
		SET @count = @count + 1;
	END WHILE;
END $$
DELIMITER ;